
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 3tee
 */
public class LowOnStock extends javax.swing.JFrame {

    /**
     * Creates new form LowOnStock
     */    
 int From,

    /**
     * Creates new form LowOnStock
     */
    To;
 ArrayList<Inventory> filteredInventory = new ArrayList<>();
    
    
    void SetBars(ArrayList<Inventory> array, int threshold) {
       setTitle("Out Of Stock Items");
       
        setSize(500, 80*array.size());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        progressPanel.setLayout(new BoxLayout(progressPanel, BoxLayout.Y_AXIS));
        int gapSize = 50;// set the layout to a vertical box layout
        progressPanel.setBorder(BorderFactory.createEmptyBorder(gapSize, gapSize, gapSize, gapSize));
        for (int i=0;i<array.size();i++) {
            JProgressBar progressBar = new JProgressBar(0, threshold); // create a progress bar with a minimum value of 0 and a maximum value of 100
            progressBar.setValue(array.get(i).getQuantity());
         //   progressBar.setForeground(Color.GREEN);
            progressBar.setBorder(BorderFactory.createEmptyBorder(5,0,5,0));
            progressBar.setStringPainted(true);
            progressBar.setString(array.get(i).getProductName()+" ("+array.get(i).getQuantity()+")"); // set the text to display inside the progress bar
          //  if (i > 0) {
            //progressPanel.add(Box.createRigidArea(new Dimension(0, 10))); // change 10 to adjust spacing
             //}
        
        progressPanel.add(progressBar);
        }
    progressPanel.revalidate();
    progressPanel.repaint();


        setVisible(true);
    }
    
    
    
    void view()
    {
        ArrayList<Integer> values = new ArrayList<>();
        for(int i=0;i<filteredInventory.size();i++)
        {
            filteredInventory.remove(i);
        }
        //From = Integer.parseInt(from.getText());
      //  To = Integer.parseInt(to.getText());
      From = 0;
      To = 30;
        AdjustStockLevels stock = new AdjustStockLevels();
        for(Inventory st : stock.inventory)
        {
            if(st.getQuantity()>=From && st.getQuantity()<=To)
            {
                filteredInventory.add(st);
                values.add(st.getQuantity());
            }
        }
        
        //filteredInventory.sort(null);
        
      //  int x = filteredInventory.get(filteredInventory.size()-1).getQuantity();
        int highest = filteredInventory.get(0).getQuantity();
      for(int i = 0 ; i<filteredInventory.size();i++)
        {
            if(filteredInventory.get(i).getQuantity()>highest)
            {
                highest = filteredInventory.get(i).getQuantity();
            }
        }
        SetBars(filteredInventory,highest);
    }
    
    
    public LowOnStock() {
        initComponents();
        int[] arr = {22,45,21,20,32};
       // addProgressBars(arr);
        view();
       // SetBars(filteredInventory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progressPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/inventory icons/out-of-stock (1).png"))); // NOI18N
        jLabel1.setText("Low Stock Products");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        progressPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel progressPanel;
    // End of variables declaration//GEN-END:variables
}
